name: Semantic Release Workflow

on:
  push:
    branches:
      - main # or master, or whichever branch you want this to run on

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        extra_args: '--dry-run' # Remove this line if you want to actually release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
